#!/usr/bin/env python3

import math

def faktorial(a):
    if a>0:
        return a * faktorial(a-1)
    else:
        return 1

if __name__ =="__main__":
    a = int(input("Zadej číslo:"))
    print(faktorial(a))

